package com.lvguanwei.emall.product.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.lvguanwei.emall.product.dao.model.ProductDO;
import com.lvguanwei.emall.product.dao.model.ProductDOExample.Criteria;
import com.lvguanwei.emall.product.dao.model.ProductDOExample.Criterion;
import com.lvguanwei.emall.product.dao.model.ProductDOExample;
import java.util.List;
import java.util.Map;

public class ProductDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String countByExample(ProductDOExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("product");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String deleteByExample(ProductDOExample example) {
        BEGIN();
        DELETE_FROM("product");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String insertSelective(ProductDO record) {
        BEGIN();
        INSERT_INTO("product");
        
        VALUES("id", "#{id,jdbcType=BIGINT}");
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            VALUES("price", "#{price,jdbcType=BIGINT}");
        }
        
        if (record.getLocation() != null) {
            VALUES("location", "#{location,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            VALUES("city", "#{city,jdbcType=VARCHAR}");
        }
        
        if (record.getProvince() != null) {
            VALUES("province", "#{province,jdbcType=VARCHAR}");
        }
        
        if (record.getIsPhysicalStore() != null) {
            VALUES("is_physical_store", "#{isPhysicalStore,jdbcType=BIT}");
        }
        
        if (record.getStoreName() != null) {
            VALUES("store_name", "#{storeName,jdbcType=VARCHAR}");
        }
        
        if (record.getStoreLocation() != null) {
            VALUES("store_location", "#{storeLocation,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDeliveryDoor() != null) {
            VALUES("is_delivery_door", "#{isDeliveryDoor,jdbcType=BIT}");
        }
        
        if (record.getIsUsedGoods() != null) {
            VALUES("is_used_goods", "#{isUsedGoods,jdbcType=BIT}");
        }
        
        if (record.getIsChangedEachother() != null) {
            VALUES("is_changed_eachother", "#{isChangedEachother,jdbcType=BIT}");
        }
        
        if (record.getIsHot() != null) {
            VALUES("is_hot", "#{isHot,jdbcType=BIT}");
        }
        
        if (record.getPopularityIndex() != null) {
            VALUES("popularity_index", "#{popularityIndex,jdbcType=BIGINT}");
        }
        
        if (record.getStatus() != null) {
            VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String selectByExample(ProductDOExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("name");
        SELECT("price");
        SELECT("location");
        SELECT("city");
        SELECT("province");
        SELECT("is_physical_store");
        SELECT("store_name");
        SELECT("store_location");
        SELECT("is_delivery_door");
        SELECT("is_used_goods");
        SELECT("is_changed_eachother");
        SELECT("is_hot");
        SELECT("popularity_index");
        SELECT("status");
        SELECT("create_time");
        SELECT("update_time");
        FROM("product");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ProductDO record = (ProductDO) parameter.get("record");
        ProductDOExample example = (ProductDOExample) parameter.get("example");
        
        BEGIN();
        UPDATE("product");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getName() != null) {
            SET("name = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            SET("price = #{record.price,jdbcType=BIGINT}");
        }
        
        if (record.getLocation() != null) {
            SET("location = #{record.location,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            SET("city = #{record.city,jdbcType=VARCHAR}");
        }
        
        if (record.getProvince() != null) {
            SET("province = #{record.province,jdbcType=VARCHAR}");
        }
        
        if (record.getIsPhysicalStore() != null) {
            SET("is_physical_store = #{record.isPhysicalStore,jdbcType=BIT}");
        }
        
        if (record.getStoreName() != null) {
            SET("store_name = #{record.storeName,jdbcType=VARCHAR}");
        }
        
        if (record.getStoreLocation() != null) {
            SET("store_location = #{record.storeLocation,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDeliveryDoor() != null) {
            SET("is_delivery_door = #{record.isDeliveryDoor,jdbcType=BIT}");
        }
        
        if (record.getIsUsedGoods() != null) {
            SET("is_used_goods = #{record.isUsedGoods,jdbcType=BIT}");
        }
        
        if (record.getIsChangedEachother() != null) {
            SET("is_changed_eachother = #{record.isChangedEachother,jdbcType=BIT}");
        }
        
        if (record.getIsHot() != null) {
            SET("is_hot = #{record.isHot,jdbcType=BIT}");
        }
        
        if (record.getPopularityIndex() != null) {
            SET("popularity_index = #{record.popularityIndex,jdbcType=BIGINT}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{record.status,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("product");
        
        SET("id = #{record.id,jdbcType=BIGINT}");
        SET("name = #{record.name,jdbcType=VARCHAR}");
        SET("price = #{record.price,jdbcType=BIGINT}");
        SET("location = #{record.location,jdbcType=VARCHAR}");
        SET("city = #{record.city,jdbcType=VARCHAR}");
        SET("province = #{record.province,jdbcType=VARCHAR}");
        SET("is_physical_store = #{record.isPhysicalStore,jdbcType=BIT}");
        SET("store_name = #{record.storeName,jdbcType=VARCHAR}");
        SET("store_location = #{record.storeLocation,jdbcType=VARCHAR}");
        SET("is_delivery_door = #{record.isDeliveryDoor,jdbcType=BIT}");
        SET("is_used_goods = #{record.isUsedGoods,jdbcType=BIT}");
        SET("is_changed_eachother = #{record.isChangedEachother,jdbcType=BIT}");
        SET("is_hot = #{record.isHot,jdbcType=BIT}");
        SET("popularity_index = #{record.popularityIndex,jdbcType=BIGINT}");
        SET("status = #{record.status,jdbcType=INTEGER}");
        SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        ProductDOExample example = (ProductDOExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String updateByPrimaryKeySelective(ProductDO record) {
        BEGIN();
        UPDATE("product");
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            SET("price = #{price,jdbcType=BIGINT}");
        }
        
        if (record.getLocation() != null) {
            SET("location = #{location,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            SET("city = #{city,jdbcType=VARCHAR}");
        }
        
        if (record.getProvince() != null) {
            SET("province = #{province,jdbcType=VARCHAR}");
        }
        
        if (record.getIsPhysicalStore() != null) {
            SET("is_physical_store = #{isPhysicalStore,jdbcType=BIT}");
        }
        
        if (record.getStoreName() != null) {
            SET("store_name = #{storeName,jdbcType=VARCHAR}");
        }
        
        if (record.getStoreLocation() != null) {
            SET("store_location = #{storeLocation,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDeliveryDoor() != null) {
            SET("is_delivery_door = #{isDeliveryDoor,jdbcType=BIT}");
        }
        
        if (record.getIsUsedGoods() != null) {
            SET("is_used_goods = #{isUsedGoods,jdbcType=BIT}");
        }
        
        if (record.getIsChangedEachother() != null) {
            SET("is_changed_eachother = #{isChangedEachother,jdbcType=BIT}");
        }
        
        if (record.getIsHot() != null) {
            SET("is_hot = #{isHot,jdbcType=BIT}");
        }
        
        if (record.getPopularityIndex() != null) {
            SET("popularity_index = #{popularityIndex,jdbcType=BIGINT}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{status,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    protected void applyWhere(ProductDOExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}