package com.lvguanwei.emall.product.dao.model;

import java.io.Serializable;
import java.util.Date;

public class ProductDO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.location
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.city
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.province
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_physical_store
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private Boolean isPhysicalStore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.store_name
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.store_location
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private String storeLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_delivery_door
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private Boolean isDeliveryDoor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_used_goods
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private Boolean isUsedGoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_changed_eachother
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private Boolean isChangedEachother;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_hot
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private Boolean isHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.popularity_index
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private Long popularityIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.status
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.update_time
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.location
     *
     * @return the value of product.location
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.location
     *
     * @param location the value for product.location
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.city
     *
     * @return the value of product.city
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.city
     *
     * @param city the value for product.city
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.province
     *
     * @return the value of product.province
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.province
     *
     * @param province the value for product.province
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_physical_store
     *
     * @return the value of product.is_physical_store
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public Boolean getIsPhysicalStore() {
        return isPhysicalStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_physical_store
     *
     * @param isPhysicalStore the value for product.is_physical_store
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setIsPhysicalStore(Boolean isPhysicalStore) {
        this.isPhysicalStore = isPhysicalStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.store_name
     *
     * @return the value of product.store_name
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.store_name
     *
     * @param storeName the value for product.store_name
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.store_location
     *
     * @return the value of product.store_location
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public String getStoreLocation() {
        return storeLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.store_location
     *
     * @param storeLocation the value for product.store_location
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setStoreLocation(String storeLocation) {
        this.storeLocation = storeLocation == null ? null : storeLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_delivery_door
     *
     * @return the value of product.is_delivery_door
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public Boolean getIsDeliveryDoor() {
        return isDeliveryDoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_delivery_door
     *
     * @param isDeliveryDoor the value for product.is_delivery_door
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setIsDeliveryDoor(Boolean isDeliveryDoor) {
        this.isDeliveryDoor = isDeliveryDoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_used_goods
     *
     * @return the value of product.is_used_goods
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public Boolean getIsUsedGoods() {
        return isUsedGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_used_goods
     *
     * @param isUsedGoods the value for product.is_used_goods
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setIsUsedGoods(Boolean isUsedGoods) {
        this.isUsedGoods = isUsedGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_changed_eachother
     *
     * @return the value of product.is_changed_eachother
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public Boolean getIsChangedEachother() {
        return isChangedEachother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_changed_eachother
     *
     * @param isChangedEachother the value for product.is_changed_eachother
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setIsChangedEachother(Boolean isChangedEachother) {
        this.isChangedEachother = isChangedEachother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_hot
     *
     * @return the value of product.is_hot
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public Boolean getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_hot
     *
     * @param isHot the value for product.is_hot
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.popularity_index
     *
     * @return the value of product.popularity_index
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public Long getPopularityIndex() {
        return popularityIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.popularity_index
     *
     * @param popularityIndex the value for product.popularity_index
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setPopularityIndex(Long popularityIndex) {
        this.popularityIndex = popularityIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.update_time
     *
     * @return the value of product.update_time
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.update_time
     *
     * @param updateTime the value for product.update_time
     *
     * @mbggenerated Tue Aug 25 18:54:18 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}